# Generated by Django 4.1.7 on 2023-03-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=1000)),
                ("tags", models.ManyToManyField(related_name="links", to="tags.tag")),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
